### ISSUE TITLE
Where should i put the endpoint?

### ISSUE THREAD

**Issue by remorses** [coopnd/fastify-apollo#13]
In express is :

`app.use('/graphql', graphqlExpress( schema ));`

in restify readme is:

`fastify.register(graphqlFastify, {schema})`

in restify where should i put the route/endpoint?
is the endpoint in the schema itself?

**Comment by coopnd** [comment]
Prefix is what you want.

```
- fastify.register(graphqlFastify, {schema})
+ fastify.register(graphqlFastify, {schema, prefix: 'graphql'})
```
